spring:
  cache:
    cache-names:
      - products
      - reviews
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: products
      filter-order: 1
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API\" }"
      url: .*
      rate-limits:
        - execute-condition:  "1==1"
          expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 3
              time: 1
              unit: minutes